### ISSUE TITLE
NodeJs

### ISSUE THREAD

**Issue by rodrigoords** [CommunityBootcamp/Maratona-BOTs#1]
Não encontrei nenhum passo a passo de configuração do ambiente com node.js, existe algum passo a passo ou até mesmo algum tipo de documentação que auxilie na configuração para acompanhar a maratona utilizando node.js ?

**Comment by cyz** [comment]
Olá @rodrigoords, o tutorial de Node está listado em no nosso readme. Você também pode acessar diretamente em: https://github.com/CommunityBootcamp/Maratona-BOTs/blob/master/QuickStart/configurando-ambiente-nodejs.md
