### ISSUE TITLE
[Duvida BotFramework-Emulator]

### ISSUE THREAD

**Issue by ICDG-InterConectDigital** [CommunityBootcamp/Maratona-BOTs#11]
Olá amigos. Estou iniciando em BotFramework. E gostaria de uma informação como faço para executar este emulador. Ficaria Grato se alguém pudesse me explicar.

**Comment by pvfigueiredo** [comment]
Caso você estiver utilizando Windows, basta instalar normalmente o emulador e, quando você rodar o código do seu bot, você abre o BotFramework-Emulator e, onde pede para efetuar o login, basta clicar em iniciar sem entrar com nenhum dado. Na barra de endereço na parte superior do messenger, você vai entrar com endereço que o seu bot lhe dá quando você o executa. Se não me engano, é algo como "http://localhost3979/api/messenges".

Já no Linux, você precisa instalar as dependências necessários através do comando npm. Como não lembro de cabeça quais são os comandos exatos, se puder me esperar, quando chegar em casa eu confiro.
Só lembro dos seguintes comandos:
npm init
npm install --save builder
npm install --save restify (para instalar o restify)
