### ISSUE TITLE
[Visual Studio for Mac não tem suporte] Limitação para usuários do Mac

### ISSUE THREAD

**Issue by antoniolazaro** [CommunityBootcamp/Maratona-BOTs#12]
Segundo a microsoft, usuários do Mac OS ainda não tem suporte para visual studio. Então, usuários do Mac devem usar a API rest ou node.js.

_The Bot Builder SDK for .NET currently supports C#. Visual Studio for Mac is not supported._

**fonte:** https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-quickstart

**Comment by Marcelo94** [comment]
Oi Antonio,
Oficialmente, o Visual Studio para Mac ainda não é suportado pela Bot Builder SDK.

Porém, um desenvolvedor disponibilizou o template abaixo que pode te ajudar. Lembro que essa não é uma solução suportada pela Microsoft.
https://github.com/User1m/botframework-template-vs-for-mac
