### ISSUE TITLE
Template Bot - Mac

### ISSUE THREAD

**Issue by pamelasantos** [CommunityBootcamp/Maratona-BOTs#2]
Uso um macbook e instalei o VS, e agora estou tentando instalar os templates em .zip no VS, mas não encontro o diretório de template.. Não encontrei nada na internet.. alguém tem alguma ideia??

**Comment by tallesviana** [comment]
Oi Pâmela,

Olha, eu usei o Open diretão. A questão é não salvar por cima do template,
eu acredito.

**Comment by cyz** [comment]
Oi Pamela,

Como o Talles comentou, o mac não tem suporte aos templates do Windows, com isso, você pode rodar diretamente, apenas atentando para ter instalado o pacote nuget do bot framework.

E @tallesviana, obrigada pela contribuição!

**Comment by leeomarques** [comment]
Olá, completei a instalação local do NODE.js, porém não entendi essa parte.

**-  Inclua suas credenciais de Microsoft App ID e App Password (você pode deixar em branco quando estiver testando localmente).**

Poderiam me explicar como faço ? e hoje terá mais aulas ? :D estou ansioso para aprender mais !!!! :D
