### ISSUE TITLE
Uma Dúvida por favor :D

### ISSUE THREAD

**Issue by leeomarques** [CommunityBootcamp/Maratona-BOTs#3]
Olá, completei a instalação local do NODE.js, porém não entendi essa parte.

**- Inclua suas credenciais de Microsoft App ID e App Password (você pode deixar em branco quando estiver testando localmente).**

Poderiam me explicar como faço ? e hoje terá mais aulas ? :D estou ansioso para aprender mais !!!! :D

**Comment by cyz** [comment]
@leeomarques entre para o grupo do facebook ou envie e-mail para maratona@microsoft.com quando você tiver dúvidas com relação ao cronograma de aulas e etc. Sobre as credenciais de APP ID, só será necessário quando você iniciar o processo de teste e publicação do seu bot e será explicado em aula 😄 

- [Grupo](https://www.facebook.com/groups/devbotsbrasil/)

**Comment by leeomarques** [comment]
Muito Obrigado :+1:

**Comment by leeomarques** [comment]
Esta em aprovação ... está pendente lá :D

**Comment by leeomarques** [comment]
Irei Fechar ... Agradeço mais uma vez a toda equipe @cyz
