### ISSUE TITLE
[Dúvida] Rest

### ISSUE THREAD

**Issue by willsilvano** [CommunityBootcamp/Maratona-BOTs#6]
Olá!

Caso eu queira trabalhar com outra linguagem de programação, Python por exemplo, e utilizar através de REST, é possível?

Ou terei que ainda configurar o ambiente C#/Nodejs?

**Comment by cyz** [comment]
É possível, você pode usar a [documentação](https://docs.microsoft.com/en-us/Bot-Framework/rest-api/bot-framework-rest-connector-api-reference) para se guiar, pois devido ao volume de demanda, estamos focando o curso em oferecer conteúdo em C# e adicionalmente, colocando referências de Node.
